jest.mock('react-native-nitro-player', () => ({
	TrackPlayer: {
		configure: jest.fn(),
		play: jest.fn(),
		pause: jest.fn(),
		seek: jest.fn(),
		getState: jest.fn().mockResolvedValue({}),
		skipToIndex: jest.fn(),
		skipToNext: jest.fn(),
		skipToPrevious: jest.fn(),
		onChangeTrack: jest.fn(),
		onPlaybackProgressChange: jest.fn(),
		onPlaybackStateChange: jest.fn(),
		onTracksNeedUpdate: jest.fn(),
		onSeek: jest.fn(),
		setRepeatMode: jest.fn(),
		getTracksNeedingUrls: jest.fn().mockResolvedValue([]),
		getActualQueue: jest.fn().mockResolvedValue([]),
		updateTracks: jest.fn(),
	},
	PlayerQueue: {
		getCurrentPlaylistId: jest.fn(),
		loadPlaylist: jest.fn().mockResolvedValue(undefined),
		getPlaylist: jest.fn(),
		createPlaylist: jest.fn(),
		addTrackToPlaylist: jest.fn(),
		addTracksToPlaylist: jest.fn(),
		removeTrackFromPlaylist: jest.fn(),
		reorderTrackInPlaylist: jest.fn(),
	},
	DownloadManager: {
		configure: jest.fn(),
		downloadTrack: jest.fn(),
		deleteTrack: jest.fn(),
		deleteDownloadedTrack: jest.fn(),
		deleteAllDownloads: jest.fn(),
		getDownloadedTrack: jest.fn().mockResolvedValue(null),
		getDownloadedTracks: jest.fn().mockResolvedValue([]),
		getAllDownloadedTracks: jest.fn().mockResolvedValue([]),
		isTrackDownloaded: jest.fn().mockReturnValue(false),
		onDownloadComplete: jest.fn(),
	},
	RepeatMode: {
		None: 'none',
		One: 'one',
		All: 'all',
	},
	TrackPlayerState: {
		Playing: 'playing',
		Paused: 'paused',
		Stopped: 'stopped',
		Buffering: 'buffering',
		None: 'none',
	},
	useNowPlaying: jest.fn().mockReturnValue({ nowPlaying: undefined }),
	useOnPlaybackProgressChange: jest.fn().mockReturnValue({ position: 0, totalDuration: 0 }),
	useOnPlaybackStateChange: jest.fn().mockReturnValue({ state: 'none' }),
	useDownloadProgress: jest.fn().mockReturnValue({ progress: 0 }),
	useDownloadedTracks: jest.fn().mockReturnValue({ downloadedTracks: [] }),
}))
