enum LoggingContext {
	Initialization = 'Initialization',
	PlaybackReporting = 'Playback Reporting',
	NitroFetch = 'Nitro Fetch',
	AutoDownload = 'Auto Download',
	PublicSystemInfo = 'Public System Info',
	Queue = 'Queue',
	QueueStorage = 'Queue Storage',
	Favorites = 'Favorites',
	UserData = 'User Data',
	Recents = 'Recents',
	Albums = 'Albums',
	Tracks = 'Tracks',
	Playlist = 'Playlist',
	InstantMix = 'Instant Mix',
	Lyrics = 'Lyrics',
	Session = 'Session',
	Authentication = 'Authentication',
	Genre = 'Genre',
	Libraries = 'Libraries',
	OtaUpdates = 'OTA Updates',
	AndroidAuto = 'Android Auto',
	Performance = 'Performance',
	Permissions = 'Permissions',
	LegacyMigration = 'Legacy Migration',
	UI = 'UI',
	MediaInfo = 'MediaInfo',
}

export default LoggingContext
